### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by Glajik** [Glajik/homepage#1]
You might want to take a look at [GitHub Flavored Markdown](https://guides.github.com/features/mastering-markdown/) and [Documenting your projects on GitHub](https://guides.github.com/features/wikis/)

## Todo
- [x] Add Description section
- [x] Add Usage section
- [x] Add Installation section
- [x] Add Table of content section
